---
title: "Deliverable 4"
author: "Michaela Bowen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Data

```{r, warning=FALSE, message=FALSE}
# Load libraries
library(readr)
library(dplyr)
library(arrow)

# Read Spotify data from GitHub
spotify_data <- read_csv("https://raw.githubusercontent.com/Mikay711/DPP_Deliv3/refs/heads/main/Processed%20Data/Spotify_Rescaled.csv")

# Preview Spotify data
head(spotify_data)


# Read Hot100 data from GitHub
hot100_data <- read_csv("https://raw.githubusercontent.com/Mikay711/DPP_Deliv3/refs/heads/main/Processed%20Data/Hot100_Rescaled.csv")

# Preview Hot100 data
head(hot100_data)

```

## One Group, One Function, One Input Variable


```{r}
# One Group, One Function, One Input Variable: Mean of energy_scaled by stream_category
output111 <- spotify_data %>%
  group_by(stream_category) %>%
  summarize(mean_energy = mean(energy_scaled, na.rm = TRUE))

# Preview the result
head(output111)

```
## Two Groups, Two Functions, One Input Variable

```{r, warning=FALSE}
# Two Groups, Two Functions, One Input Variable
output221 <- spotify_data %>%
  group_by(stream_category, key) %>%
  summarize(
    mean_danceability = mean(danceability_scaled, na.rm = TRUE),
    sum_energy = sum(energy_scaled, na.rm = TRUE),
    .groups = "drop"
  )

# Preview the output
head(output221)

```
## One Group, Two Input Variables, Different Functions
```{r}
# One Group, Two Input Variables, Different Functions
output12f1f2 <- spotify_data %>%
  group_by(stream_category) %>%
  summarize(
    median_danceability = median(danceability_scaled, na.rm = TRUE),
    sd_energy = sd(energy_scaled, na.rm = TRUE)
  )

# Preview the result
head(output12f1f2)


```

## Save Spotify Output111

```{r}
# Save output111
write_csv(output111, "finalOutput/output111.csv")
saveRDS(output111, "finalOutput/output111.RDS")
write_parquet(output111, "finalOutput/output111.parquet")

```

## Save Spotify Ouput 221
```{r}

# Save output221
write_csv(output221, "finalOutput/output221.csv")
saveRDS(output221, "finalOutput/output221.RDS")
write_parquet(output221, "finalOutput/output221.parquet")


```

## Save Spotify Output12f1f2
```{r}
# Save output12f1f2
write_csv(output12f1f2, "finalOutput/output12f1f2.csv")
saveRDS(output12f1f2, "finalOutput/output12f1f2.RDS")
write_parquet(output12f1f2, "finalOutput/output12f1f2.parquet")

```





